"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TOKEN_MINT = exports.SLIPPAGE = exports.JITO_FEE = exports.JITO_MODE = exports.SOL_AMOUNT_TO_DISTRIBUTE = exports.DISTRIBUTE_WALLET_NUM = exports.SELL_INTERVAL_MAX = exports.SELL_INTERVAL_MIN = exports.BUY_INTERVAL_MAX = exports.BUY_INTERVAL_MIN = exports.BUY_LOWER_PERCENT = exports.BUY_UPPER_PERCENT = exports.DISTRIBUTE_INTERVAL_MIN = exports.DISTRIBUTE_INTERVAL_MAX = exports.RPC_WEBSOCKET_ENDPOINT = exports.RPC_ENDPOINT = exports.PRIVATE_KEY = void 0;
const utils_1 = require("../utils");
exports.PRIVATE_KEY = (0, utils_1.retrieveEnvVariable)('PRIVATE_KEY');
exports.RPC_ENDPOINT = (0, utils_1.retrieveEnvVariable)('RPC_ENDPOINT');
exports.RPC_WEBSOCKET_ENDPOINT = (0, utils_1.retrieveEnvVariable)('RPC_WEBSOCKET_ENDPOINT');
exports.DISTRIBUTE_INTERVAL_MAX = Number((0, utils_1.retrieveEnvVariable)('DISTRIBUTE_INTERVAL_MAX'));
exports.DISTRIBUTE_INTERVAL_MIN = Number((0, utils_1.retrieveEnvVariable)('DISTRIBUTE_INTERVAL_MIN'));
exports.BUY_UPPER_PERCENT = Number((0, utils_1.retrieveEnvVariable)('BUY_UPPER_PERCENT'));
exports.BUY_LOWER_PERCENT = Number((0, utils_1.retrieveEnvVariable)('BUY_LOWER_PERCENT'));
exports.BUY_INTERVAL_MIN = Number((0, utils_1.retrieveEnvVariable)('BUY_INTERVAL_MIN'));
exports.BUY_INTERVAL_MAX = Number((0, utils_1.retrieveEnvVariable)('BUY_INTERVAL_MAX'));
exports.SELL_INTERVAL_MIN = Number((0, utils_1.retrieveEnvVariable)('SELL_INTERVAL_MIN'));
exports.SELL_INTERVAL_MAX = Number((0, utils_1.retrieveEnvVariable)('SELL_INTERVAL_MAX'));
exports.DISTRIBUTE_WALLET_NUM = Number((0, utils_1.retrieveEnvVariable)('DISTRIBUTE_WALLET_NUM'));
exports.SOL_AMOUNT_TO_DISTRIBUTE = Number((0, utils_1.retrieveEnvVariable)('SOL_AMOUNT_TO_DISTRIBUTE'));
exports.JITO_MODE = (0, utils_1.retrieveEnvVariable)('JITO_MODE') === 'true';
exports.JITO_FEE = Number((0, utils_1.retrieveEnvVariable)('JITO_FEE'));
exports.SLIPPAGE = Number((0, utils_1.retrieveEnvVariable)('SLIPPAGE'));
exports.TOKEN_MINT = (0, utils_1.retrieveEnvVariable)('TOKEN_MINT');
